In [1]:
import dgl

DGL backend not selected or invalid.  Assuming PyTorch for now.


Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)


/home/northja/miniconda3/envs/ML/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import dgl
import numpy as np
import torch

In [3]:
g = dgl.graph(([0, 0, 0, 0, 0], [1, 2, 3, 4, 5]), num_nodes=6)
# Equivalently, PyTorch LongTensors also work.
#g = dgl.graph((torch.LongTensor([0, 0, 0, 0, 0]), torch.LongTensor([1, 2, 3, 4, 5])), num_nodes=6)

# You can omit the number of nodes argument if you can tell the number of nodes from the edge list alone.
#g = dgl.graph(([0, 0, 0, 0, 0], [1, 2, 3, 4, 5]))

In [4]:
g

Graph(num_nodes=6, num_edges=5,
      ndata_schemes={}
      edata_schemes={})

In [5]:
print(g.edges())

(tensor([0, 0, 0, 0, 0]), tensor([1, 2, 3, 4, 5]))


In [6]:
print(g.nodes())

tensor([0, 1, 2, 3, 4, 5])


In [7]:
## Assign node features to graph nodes

In [8]:
g.ndata['cs_13C'] = 120 * torch.randn(6,1)

In [9]:
g.ndata['cs_1H'] = 8 * torch.randn(6,1)

In [10]:
print(g.ndata['cs_1H'])

tensor([[-5.7315],
        [ 0.1667],
        [ 0.5825],
        [13.5754],
        [11.5672],
        [ 3.3267]])


In [11]:
g.ndata['cs_13C']

tensor([[-123.6864],
        [ -78.9506],
        [  92.4675],
        [ 159.7291],
        [ 172.0837],
        [  -9.9751]])

In [13]:
g.edata['bonding'] = torch.randn(5,1)

In [14]:
g.edata['bonding']

tensor([[ 0.1090],
        [ 0.0287],
        [ 0.3822],
        [ 0.4775],
        [-1.8701]])

In [15]:
g.out_degrees(0)

5